name: 'Setup Dojo'
description: 'Sets up the dojo-engine toolset to the action'
inputs:
  version:
    description: 'The version of the dojo engine to pull'
    default: 'v1.0.1'

branding:
  icon: "monitor"
  color: "red"

runs:
  using: "composite"
  steps:
  - name: 'Install dojoup'
    shell: bash
    run: |-
      curl -L https://install.dojoengine.org | bash
      echo "-----"
      BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
      DOJO_DIR=${DOJO_DIR-"$BASE_DIR/.dojo"}
      export PATH="$PATH:$DOJO_DIR/bin"
      $DOJO_DIR/bin/dojoup install ${{ inputs.version }}
      echo "$DOJO_DIR/toolchain/${{ inputs.version }}" >> $GITHUB_PATH
      echo "------"
      ls -la "$DOJO_DIR/toolchain/${{ inputs.version }}"
      $DOJO_DIR/bin/sozo --version
