name: "Setup Dojo"
description: "Sets up the dojo-engine toolset to the action"
inputs:
  version:
    description: "The version of the dojo engine to pull"
    default: "v1.7.0-alpha.2"

branding:
  icon: "monitor"
  color: "red"

runs:
  using: "composite"
  steps:
    - name: "Install Dojo"
      shell: bash
      run: |-
        # Run the install script from the action's directory
        "${{ github.action_path }}/install-dojo.sh" ${{ inputs.version }}

        # Add /usr/local/bin to PATH if not already there
        echo "/usr/local/bin" >> $GITHUB_PATH

        # Verify installation
        echo "------"
        sozo --version
