name: 'Setup Dojo'
description: 'Sets up the dojo-engine toolset to the action'
inputs:
  version:
    description: 'The version of the dojo engine to pull'

runs:
  using: "composite"
  steps:
  - name: 'Install dojoup'
    shell: bash
    run: |-
      curl -L https://install.dojoengine.org | bash
      echo "-----"
      export PATH="$PATH:$HOME/.dojo/bin"
      $HOME/.dojo/bin/dojoup --version ${{ inputs.version }}
